# Generated by Django 5.1.7 on 2025-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_images', models.ImageField(upload_to='')),
                ('news_title', models.CharField(max_length=256)),
            ],
        ),
    ]
