# Generated by Django 5.1.7 on 2025-03-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allnews',
            old_name='news_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='allnews',
            old_name='news_title',
            new_name='title',
        ),
    ]
