# Generated by Django 5.1.7 on 2025-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_rename_news_images_allnews_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_news_images/')),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='allnews',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
