# Generated by Django 5.1.7 on 2025-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_mainnews_alter_allnews_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='created_at',
            field=models.DateField(),
        ),
    ]
