# Generated by Django 5.1.7 on 2025-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0007_alter_allnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='all_news_images/'),
        ),
    ]
