# Generated by Django 5.1.7 on 2025-03-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0008_alter_allnews_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllNews',
        ),
    ]
