# Generated by Django 5.1.7 on 2025-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0009_delete_allnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='all_news_images/')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
