# Generated by Django 5.1.7 on 2025-03-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0011_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured_images/')),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
