# Generated by Django 5.1.7 on 2025-03-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0012_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_images/')),
                ('category', models.CharField(max_length=50)),
                ('published_at', models.DateField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='entertainment_images/')),
                ('category', models.CharField(max_length=50)),
                ('published_at', models.DateField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='latest_images/')),
                ('category', models.CharField(max_length=50)),
                ('published_at', models.DateField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='popular_images/')),
                ('category', models.CharField(max_length=50)),
                ('published_at', models.DateField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports_images/')),
                ('category', models.CharField(max_length=50)),
                ('published_at', models.DateField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='technology_images/')),
                ('category', models.CharField(max_length=50)),
                ('published_at', models.DateField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='featured',
            old_name='created_at',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='mainnews',
            old_name='created_at',
            new_name='published_at',
        ),
    ]
