# Generated by Django 5.1.7 on 2025-03-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0013_business_entertainment_latest_popular_sports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popular',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
