# Generated by Django 5.1.7 on 2025-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0014_alter_latest_content_alter_popular_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allnews',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='featured',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='latest',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='popular',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sports',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
