# Generated by Django 5.1.7 on 2025-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0015_alter_allnews_title_alter_business_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sports',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
