# Generated by Django 5.1.7 on 2025-03-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0016_business_content_entertainment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
