# Generated by Django 5.1.7 on 2025-03-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0017_technology_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('published_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Single_news_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='single_news_images/')),
                ('single_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newsroom.single_news')),
            ],
        ),
    ]
