# Generated by Django 5.1.7 on 2025-03-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0018_single_news_single_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_news_image',
            name='single_news',
        ),
        migrations.DeleteModel(
            name='Single_news',
        ),
        migrations.DeleteModel(
            name='Single_news_image',
        ),
    ]
