# Generated by Django 5.1.7 on 2025-03-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0019_remove_single_news_image_single_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('published_at', models.DateField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='single_news_images/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='single_news_images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='newsroom.single_news')),
            ],
        ),
    ]
