# Generated by Django 5.1.7 on 2025-03-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0020_single_news_newscontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsContent',
        ),
        migrations.DeleteModel(
            name='Single_news',
        ),
    ]
