# Generated by Django 5.1.7 on 2025-03-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0021_delete_newscontent_delete_single_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_images/')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
