# Generated by Django 5.1.7 on 2025-03-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0022_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
