# Generated by Django 5.1.7 on 2025-03-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0023_comment_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetİnTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
