# Generated by Django 5.1.7 on 2025-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0024_geti_ntouch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geti̇ntouch',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
