# Generated by Django 5.1.6 on 2025-03-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0026_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('followers', models.PositiveIntegerField()),
                ('icons', models.CharField(max_length=20)),
                ('bg_color', models.CharField(max_length=20)),
            ],
        ),
    ]
