# Generated by Django 5.1.7 on 2025-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0027_follow_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_us',
            name='followers',
            field=models.CharField(max_length=255),
        ),
    ]
