# Generated by Django 5.1.7 on 2025-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0028_alter_follow_us_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow_us',
            name='platform_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
