# Generated by Django 5.1.7 on 2025-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0029_follow_us_platform_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
