# Generated by Django 5.1.7 on 2025-03-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0030_categories_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow_us',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
