# Generated by Django 5.1.7 on 2025-03-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0031_follow_us_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_us',
            name='is_featured',
        ),
    ]
