# Generated by Django 5.1.7 on 2025-03-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0032_remove_follow_us_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
