# Generated by Django 5.1.7 on 2025-03-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0034_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='is_featured',
        ),
    ]
