# Generated by Django 5.1.7 on 2025-04-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0035_remove_tags_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
