# Generated by Django 5.1.7 on 2025-04-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0037_header_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_info',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
