# Generated by Django 5.1.7 on 2025-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0039_header_info_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header_info',
            old_name='link',
            new_name='link_currency',
        ),
        migrations.AddField(
            model_name='header_info',
            name='link_weather',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
