# Generated by Django 5.1.6 on 2025-04-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0041_allnews_link_business_link_categories_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allnews',
            name='link',
        ),
        migrations.RemoveField(
            model_name='business',
            name='link',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='link',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='link',
        ),
        migrations.RemoveField(
            model_name='latest',
            name='link',
        ),
        migrations.RemoveField(
            model_name='mainnews',
            name='link',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='link',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='link',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='link',
        ),
    ]
