# Generated by Django 5.1.7 on 2025-04-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0043_allnews_link_business_link_categories_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
