# Generated by Django 5.1.7 on 2025-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0044_tags_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='single_news_images/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('published_at', models.DateField()),
            ],
        ),
    ]
