# Generated by Django 5.1.7 on 2025-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0045_single_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_news',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
