# Generated by Django 5.1.7 on 2025-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0046_single_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_news',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='single_news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='single_news_images/'),
        ),
    ]
