# Generated by Django 5.1.7 on 2025-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0047_rename_image_single_news_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_news',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='single_news',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
