# Generated by Django 5.1.7 on 2025-04-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0048_alter_single_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnews',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allnews',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
